name: build_package_LUNAR

on:
  push:
   branches:
      - "2.5-evo"
      - "dev-release"
      - "release"
      - "debug"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    container:
      image: docker://ubuntu:lunar
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          apt update
          apt install -y git sudo

      - name: clone OpenHD
        run: |
          git clone -b ${{ github.ref_name }} https://github.com/OpenHD/OpenHD --recursive
          cd OpenHD  

      - name: Install Dependencies
        run: |
          ls
          cd OpenHD
          apt install -y python3-pip
          pip install cloudsmith-api --break-system-packages
          pip install cloudsmith-cli --break-system-packages
          ./install_build_dep.sh ubuntu-x86

      - name: Build with make
        run: |
          cd OpenHD
          ./package.sh standard x86_64 ubuntu lunar

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "OpenHD"
          path: |
            OpenHD/*.deb
            *.log
          if-no-files-found: error

      - name: Push
        run: |
          ls -a
          cloudsmith push deb  -k ${{ secrets.CLOUDSMITH_API_KEY }} openhd/${{ github.ref_name }}/ubuntu/lunar OpenHD/*.deb
