name: Build NVIDA (AGX) online

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Emulating Jetson
      id: qemu
      uses: pguyot/arm-runner-action@main
      with:
        base_image: https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jetson_xavier_nx/jetson-nx-jp461-sd-card-image.zip
        cpu: cortex-a53
        bootpartition:
        rootpartition: 1
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: OpenHD
        import_github_env: true
        commands: |
          cd /opt/OpenHD
          rm /etc/apt/sources.list.d/nvidia-l4t-apt-source.list
          apt update
          apt install curl -y
          curl -1sLf 'https://dl.cloudsmith.io/public/openhd/enterprise/setup.deb.sh' | sudo -E bash
          apt upgrade -y
          apt install -y cmake ruby-ohd
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install gcc-11 g++-11 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11
          mkdir -p /usr/local/share/openhd/
          touch /usr/local/share/openhd/joyconfig.txt
          sudo ./install_build_dep.sh rock5
          cd /opt
          cd OpenHD
          chown -R root:root ../OpenHD
          sudo ./package.sh standard arm64 ubuntu bionic

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "OpenHD"
        path: |
          OpenHD/*.deb

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "enterprise"
        distro: "ubuntu"
        release: "bionic"
        republish: "true" # needed ONLY if version is not changing
        file: "OpenHD/*.deb"

