name: build_package_rock5

on: 
  push:
    paths-ignore:
      - 'LICENSE'

jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    
             
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Building OpenHD in CHROOT
        run: |
          git clone https://github.com/OpenHD/ChrootCompilationTest /opt/ChrootCompilationTest
          mkdir -p /opt/ChrootCompilationTest/additionalFiles
          git clone https://github.com/OpenHD/OpenHD -b 2.3-rock /opt/ChrootCompilationTest/additionalFiles/ --recursive
          echo $CLOUDSMITH_API_KEY > /opt/ChrootCompilationTest/additionalFiles/cloudsmith_api_key.txt
          cd /opt/ChrootCompilationTest/
          sudo bash install_dep.sh
          sudo bash build.sh rock5 $API_KEY
