name: Build RPI

on:
  push:
    branches: [ master,"rapha-test", "2.0", "2.2.3-evo", "2.2.3-evo-rapha" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2
      id: build_image
      with:
        base_image: raspios_lite:latest
        image_additional_mb: 4000
        copy_repository_path: /opt
        copy_artifact_path: Open.HD
        import_github_env: true
        commands: |
            ls -a
            cd /opt
            cd Open.HD
            sudo apt update
            curl -1sLf 'https://dl.cloudsmith.io/public/openhd/openhd-2-2-evo/setup.deb.sh' | sudo -E bash
            mkdir -p /usr/local/share/openhd/
            touch /usr/local/share/openhd/joyconfig.txt
            sudo apt update
            sudo ./install_dep.sh
            cd /opt
            git clone https://github.com/OpenHD/Arducam-Pivariety-V4L2-Driver
            cd Arducam-Pivariety-V4L2-Driver
            cd Release
            cd /opt
            cd Open.HD
            sudo ./package.sh armhf raspbian bullseye

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD"
        path: |
          Open.HD/*.deb
        if-no-files-found: error

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-dev"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "Open.HD/*.deb"
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
