name: simple_build_test

# @Rapha please keep this one without any packaging or similar ;)
# NOTE: This test only checks if the code in the repository builds under ubuntu x86 (dependencies installed)
# Which is - simply put - the most basic test. If this test fails, there is something wrong with the code.

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    #runs-on: ubuntu-18.04
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo ./install_dep_ubuntu20.sh
      - name: Build with make
        run: |
          cd OpenHD
          ./build_cmake.sh

      #- name: Run as air, but limited to X seconds
      #  run: |
      #    sudo ./OpenHD/build/openhd -a -r 20
      #- name: Run as ground, but limited to X seconds
      #  run: |
      #    sudo ./OpenHD/build/openhd -a -g 20
